### ISSUE TITLE
Calendar Administration doesn't allow creating calendars

### ISSUE THREAD

**Issue by laurenra7** [Jasig/CalendarPortlet#83]
To replicate, got to Calendar portlet, click on title to maximize and reveal "Calendar administration" link.

1. Click on "Calendar administration"
2. Click on "+ Add a calendar"
3. Enter Calendar functional name and Calendar type
4. Click on "Next" button

Try adding a calendar on this page, and no calendar is saved.

**Comment by bjagg** [comment]
After far too long of trial and error, I have a potential fix. In `createCalendarDefinition.jsp`, the `form:form` tag overwrites the `action` parameter. The fix is to add `<input type="hidden" id="action" name="pP_action" value="createCalendarDefinition2"/>`. I have also added `modelAttribute="calendarDefinitionForm"` to the `form:form` tag, but I am not sure it was necessary.

N.B. While testing, I attempted to convert this from a Request to an Action URL. This was to address the issue around the `action` parameter disappearing. For some reason, the csrf token would be added to the URL parameters, but would then use `&amp;` instead of `&` before the `pP_action` parameter, essentially breaking the request. Further investigation may be warranted.

Should have a PR submitted tomorrow morning.
